config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :projects, only: [:show]
  end

  resources :projects, only: [:index, :show, :new, :create] do
    resources :releases, shallow: true do
      resources :notices, shallow: true
    end
  end

  get "signup" => "registrations#new", as: :signup
  post "signup" => "registrations#create", as: :registrations

  get "signin" => "sessions#new", as: :signin
  post "signin" => "sessions#create", as: :sessions
  get "logout" => "sessions#destroy", as: :logout

  constraints Constraints::Authenticated.new do
    root to: "projects#index"
  end

  get "widget.js", to: "assets#show", id: "widget"
  get "widget.css", to: "assets#show", id: "widget"

  root to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  VIEW = 'VIEW'
  THUMBS_UP = 'THUMBS_UP'
  THUMBS_DOWN = 'THUMBS_DOWN'

  belongs_to :notice

  validates :type, inclusion: { in: [VIEW, THUMBS_UP, THUMBS_DOWN] }
end

app/models/notice.rb
class Notice < ApplicationRecord
  BODY_TEMPLATE =
    <<-EOS
    We've just lent **a new cool feature**. Check it out! 💥
    EOS

  belongs_to :release
  has_many :events

  validates :body, presence: true
  validates :target_element_selector, presence: true

  def views_count
    events.where(name: Event::VIEW).count
  end
end

app/models/project.rb
class Project < ApplicationRecord
  before_create :renew_api_key

  has_many :collaborations
  has_many :users, through: :collaborations
  has_many :releases

  validates :name, presence: true

  def renew_api_key
    self.api_key = SecureRandom.hex(8)
  end
end

app/models/release.rb
class Release < ApplicationRecord
  BODY_TEMPLATE =
<<-EOS
### Features 💥

- Version navigation.

### Bugfixes 🔥

- Fix typos in the recent template.
EOS

  belongs_to :project
  has_many :notices

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :collaborations
  has_many :projects, through: :collaborations

  validates :email, uniqueness: true, presence: true, email: true
  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :display_name, presence: true
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :require_login

  def show
    respond_to do |format|
      format.js { redirect_to ActionController::Base.helpers.asset_pack_path("#{params[:id]}.js") }
      format.css { redirect_to ActionController::Base.helpers.asset_pack_path("#{params[:id]}.css") }
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  def show
  end

  def new
    @release = Release.find params[:release_id]
    @notice = @release.notices.build body: Notice::BODY_TEMPLATE

    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @release = Release.find params[:release_id]
    @notice = @release.notices.build notice_params

    respond_to do |format|
      if @notice.save
        format.js
      else
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @notice.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def notice_params
    params.require(:notice).permit(:heading, :body, :target_element_selector)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_projects, only: [:index, :new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    if @projects.empty?
      redirect_to new_project_url
    end
  end

  def show
    @releases = @project.releases.order(date: :desc)
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      ActiveRecord::Base.transaction do
        if @project.save
          current_user.projects << @project

          @project.releases.create name: 'v1.0.0', date: Time.now, body: Release::BODY_TEMPLATE

          format.html { redirect_to @project }
        else
          format.html { render :new }
        end
      end
    end
  end

  private
    def set_projects
      @projects = current_user.projects.order(:name)
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:edit, :update, :destroy]

  def new
    @project = Project.find params[:project_id]
    @release = @project.releases.build name: 'v1.0.0', date: Time.now, body: Release::BODY_TEMPLATE

    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @project = Project.find params[:project_id]
    @release = @project.releases.build release_params

    respond_to do |format|
      if @release.save
        format.js
      else
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @release.update(release_params)
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @release.destroy

    respond_to do |format|
      format.js
    end
  end

 private

  def set_release
    @release = Release.find(params[:id])
  end

  def release_params
    params.require(:release).permit(:name, :date, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def create
    user = login(params[:email], params[:password])

    if user
      redirect_back_or_to root_url
    else
      flash.now.alert = "Email or password was invalid"

      render :new
    end
  end

  def destroy
    logout

    redirect_to signin_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  GREETINGS = [
    'Sunday Funday! ⭐️',
    'Happy Monday! 🍃',
    'Happy Tuesday! ☘',
    'We’re half way through week! 🚀',
    'It’s almost Friday! 🔥',
    'Thank God it’s Friday! 🍺',
    'Let’s get party! 🎉',
  ];

  def bem_class(*args)
    classes = []

    args.each do |arg|
      case arg
      when String
        classes.push(arg) if arg.strip.size > 0
      when Hash
        arg.each do |k, v|
          classes.push(k.to_s) if !!v == true
        end
      when Array
        classes.push(dom_class(*arg))
      end
    end

    classes.join(" ")
  end

  def m(markdown)
    content_tag :div, Kramdown::Document.new(markdown).to_html.html_safe, class: "markdown"
  end

  def greetings
    GREETINGS[Time.now.wday]
  end

  def timeline_button(url, icon, html_options)
    link_to url, html_options.merge(class: 'timeline-button') do
      content_tag :i, '', 'data-feather': icon
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
  def release_date(release)
    if 1.week.ago < release.date && release.date < Time.now
      "#{time_ago_in_words release.date} ago"
    else
      release.date.strftime('%a, %b %d · %I:%M %p')
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Changelog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if current_user %>
      <div class="application-layout__header">
        <%= render 'shared/application-header' %>
      </div>
    <% end %>

    <div class="application-layout__content">
      <% flash.each do |name, text| %>
        <%= content_tag :div, text, class: "flash flash--#{name}" %>
      <% end %>

      <%= yield %>
    </div>

    <script>
      window.changelogSettings = {
        apiKey: '<%= Rails.env === 'production' ? '41bbf3fa6cbd92d2' : 'dce23f435684614d' %>',
      };
    </script>

    <script src="/widget.js"></script>
  </body>
</html>

app/views/shared/_application-header.html.erb
<div class="application-header">
  <div class="application-header__greetings">
    <%= greetings %>
  </div>

  <div class="application-header__user">
    <div class="application-header__menu-item">
      Logged in as <%= current_user.display_name %>
    </div>

    <div class="application-header__menu-item js-switch-project">
      <%= link_to "Switch project", projects_path %>
    </div>

    <div class="application-header__menu-item">
      <%= link_to "Log out", logout_path %>
    </div>
  </div>
</div>

app/views/shared/_application_header.html.erb
<div class="application-header">
  <div class="application-header__user">
    Logged in as <%= current_user.display_name %> · <%= link_to "Log out", logout_path %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="<%= bem_class('card', "card--elevation-#{local_assigns[:elevation]}": local_assigns[:elevation], 'card--interactive': local_assigns[:interactive], 'card--transparent': local_assigns[:transparent], 'card--justify': local_assigns[:justify]) %>">
  <%= yield %>
</div>

app/views/shared/_hr.html.erb
<div class="hr">
  <hr class="hr__line">

  <% if local_assigns[:heading].present? %>
    <div class="hr__heading">
      <%= local_assigns[:heading] %>
    </div>
  <% end %>

  <hr class="hr__line">
</div>

app/views/shared/_new-release.html.erb
<%
  anchor = timeline_button new_project_release_path(project), 'plus', remote: true
%>

<div class="new-release" id="new_release">
  <%= render 'shared/timeline', anchor: anchor do %>
    <div data-controller="inplace-editing" data-target="inplace-editing.content" id="new_release_form">
      <div class="new-release__content">
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_notice-actions.html.erb
<div class="notice-actions">
  <%= link_to edit_notice_path(notice), remote: true, title: "Edit", class: "notice-actions__action" do %>
    <i data-feather="edit"></i>
  <% end %>

  <%= link_to notice, method: :delete, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete", class: "notice-actions__action" do %>
    <i data-feather="trash-2"></i>
  <% end %>
</div>

app/views/shared/_notice.html.erb
<div class="notice" data-controller="inplace-editing" data-target="inplace-editing.content" id="<%= dom_id(notice) %>">
  <div class="notice__preview">
    <%= render 'shared/notice-popover', notice: notice %>
  </div>

  <div class="notice__panel">
    <div class="stats">
      <div class="stats__item">
        <div class="stats__legend">
          Views
        </div>

        <div class="stats__value">
          <%= notice.views_count %>
        </div>
      </div>

      <div class="stats__item">
        <div class="stats__legend">
          Reactions
        </div>

        <div class="stats__value">
          <%= notice.views_count %>
        </div>
      </div>

      <div class="stats__item">
        <div class="stats__legend stats__legend--emoji">
          👍
        </div>

        <div class="stats__value">
          <%= notice.views_count %>%
        </div>
      </div>

      <div class="stats__item">
        <div class="stats__legend stats__legend--emoji">
          👎
        </div>

        <div class="stats__value">
          <%= notice.views_count %>%
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_recent-releases-timeline.html.erb
<%
  anchor = render('shared/timeline-anchor', url: '/', icon: 'git-commit')
%>

<div class="recent-releases-timeline">
  <%= render 'shared/timeline', anchor: anchor, content_target: "release.post" do %>
    <div class="recent-releases-timeline__content">
      <%= render 'shared/hr', heading: 'Previous releases' %>
    </div>
  <% end %>
</div>

app/views/shared/_release-actions.html.erb
<div class="release-actions">
  <%= link_to edit_release_path(release), remote: true, class: 'release-actions__action' do %>
    <i data-feather="edit"></i>
  <% end %>

  <%= link_to release, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'release-actions__action' do %>
    <i data-feather="trash-2"></i>
  <% end %>
</div>

app/views/shared/_release-line.html.erb
<div class="release-line">
  <% if local_assigns.has_key? :anchor_url %>
    <%= link_to anchor_url, class: "release-line__anchor"  do %>
      <i data-feather="link"></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_release-post.html.erb
<div class="release-post">
  <h3 class="release-post__name">
    <%= release.name %>

    <div class="release-post__actions">
      <%= render 'shared/release-actions', release: release %>
    </div>
  </h3>

  <div class="release-post__body">
    <%=m release.body %>
  </div>
</div>

app/views/shared/_release.html.erb
<%
  anchor = render("shared/timeline-anchor", url: "/")
%>

<div class="release" id="<%= dom_id release %>">
  <%= render "shared/timeline", label: release_date(release), anchor: anchor do %>
    <div class="release--post" data-controller="inplace-editing" data-target="inplace-editing.content" id="<%= dom_id(release, :post) %>">
      <%= render "shared/release-post", release: release %>
    </div>

    <div class="release--notices">
      <% if release.notices.any? %>
        <%= render "shared/hr", heading: "Release popover notices" %>
      <% end %>

      <% release.notices.each do |notice| %>
        <%= render "shared/notice", notice: notice %>
      <% end %>

      <div data-controller="inplace-editing" data-target="inplace-editing.content" id="<%= dom_id release, :new_notice %>">
        <%= render "shared/new-notice", release: release %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_timeline-anchor.html.erb
  <%= link_to url, class: "timeline-anchor"  do %>
    <i data-feather="<%= local_assigns[:icon] || "link" %>"></i>
  <% end %>

app/views/shared/_timeline.html.erb
<div class="timeline">
  <div class="timeline__sidebar">
    <% if local_assigns.has_key? :label %>
      <div class="timeline__label">
        <%= label %>
      </div>
    <% end %>
  </div>

  <div class="timeline__anchor">
    <% if local_assigns.has_key? :anchor %>
      <%= anchor %>
    <% end %>

    <%= content_tag :div, '', class: 'timeline__line' %>
  </div>

  <div class="timeline__content">
    <%= yield %>
  </div>
</div>